FROM python:3.6.5-slim

# install netcat
RUN apt-get update \
  && apt-get -y install netcat \
  && apt-get clean

# set working directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# add requirements
COPY ./requirements.txt /usr/src/app/requirements.txt

# install requirements
RUN pip install -r requirements.txt

# add entrypoint.sh
COPY ./entrypoint.heroku.sh /usr/src/app/entrypoint.heroku..sh

# add app
COPY . /usr/src/app

# run server
CMD ["./entrypoint.heroku.sh"]
