version: '3.5'

services:
  web:
    image: web
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - '.:/usr/src/app'
    ports:
      - 5002:5000
    environment:
      - APP_NAME=race-support-backend
      - FLASK_DEBUG=1
      - PYTHONUNBUFFERED=0
      - APP_SETTINGS=project.server.config.ProductionConfig
      - DATABASE_URL=postgres://postgres:postgres@race-db:5432/dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@race-db:5432/test
      - SECRET_KEY=change_me_in_prod
    depends_on:
      - race-db

  race-db:
    container_name: race-db
    build:
      context: ./project/server/db
      dockerfile: Dockerfile
    ports:
      - 5436:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
