"""empty message

Revision ID: 500cf61674df
Revises: 
Create Date: 2019-05-16 11:13:13.563244

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '500cf61674df'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('riders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('usac', sa.String(length=255), nullable=False),
    sa.Column('bib', sa.String(length=255), nullable=False),
    sa.Column('event', sa.String(length=255), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('checked_in', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bib'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('event'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('usac')
    )
    op.add_column('users', sa.Column('created_on', sa.DateTime(), nullable=False))
    op.drop_column('users', 'registered_on')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('registered_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('users', 'created_on')
    op.drop_table('riders')
    # ### end Alembic commands ###
